pfeCLS_website/Models/Login.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

pfeCLS_website/Controllers/AdminLogController.cs
using Microsoft.Ajax.Utilities;
using pfeCLS_website.Extensions;
using pfeCLS_website.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;



namespace pfeCLS_website.Controllers
{
    public class AdminLogController : Controller
    {

        private DbContacts db = new DbContacts();
        private DbInscriptions dbI = new DbInscriptions();
        private DBranches dbR = new DBranches();
        private DbUtilisateurs dbU = new DbUtilisateurs();
        private DbCategories dbCg = new DbCategories();
        private DbOffres dbO = new DbOffres();

        public ActionResult Annonces(string searching)
        {
            this.AddNotification("Choisi la categorie que vous voullez et coupier sur la zone de recherche", NotificationType.INFO);
            //ViewBag.categorie_id = new SelectList(dbO.Categories, "Id_Cat", "Nom_Cat");
            return View(dbO.Offres.Where(O => O.Categorie.Nom_Cat.Contains(searching) || searching == null).ToList());



            //return View(dbO.Offres.ToList());
        }
        //[HttpPost]
        //public ActionResult Annonces(string categorie_id,string searching)
        //{

        //    ViewBag.categorie_id = new SelectList(dbO.Categories, "Id_Cat", "Nom_Cat",categorie_id);
        //    //if (!string.IsNullOrWhiteSpace(categorie_id))
        //    //{
        //    //    return View();
        //    //}

        //    //return View(dbO.Offres.Where(O =>O.Id_Cat.ToString() ==categorie_id).ToList());
        //    return View(dbO.Offres.Where(Ca => Ca.Categorie.Nom_Cat.Contains(searching) || searching == null).ToList());
        //}

    
        // GET: IndexLog
        [Authorize]
        public ActionResult Index()
        {

            this.AddNotification("SALUT", NotificationType.INFO);
            return View();
        }
     
  public ActionResult Login()
        {
            return View();
        }
       
    
  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Utilisateur model, string returnUrl)
        {

            DbUtilisateurs db = new DbUtilisateurs();
            try
            {
                var dataItem = db.Utilisateurs.Where(x => x.Nom_Uti == model.Nom_Uti && x.motPasse == model.motPasse).First();
                if (dataItem != null)
                {
                    FormsAuthentication.SetAuthCookie(dataItem.Nom_Uti, false);
                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/") && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        this.AddNotification("LOGIN REUSSITE", NotificationType.SUCCESS);
                        return RedirectToAction("Index");


                    }
                }
            }
            catch (Exception)
            {
                this.AddNotification("VERIFIER VOS INFORMATIONS !", NotificationType.ERROR);
                this.AddNotification("LOGIN ECHOUE !", NotificationType.WARNING);

                return View("Login");
            }
            return View();







        }
        //--------------------------------Utilisateurs ----------------------------------------------------------------
        [Authorize]
        // GET: Utilisateurs
        public ActionResult ListUtili()
        {
            return View(dbU.Utilisateurs.ToList());
        }
        [Authorize]
        // GET: Utilisateurs/Details/5
        public ActionResult DetailsUtili(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur utilisateur = dbU.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }
        [Authorize]
        // GET: Utilisateurs/Create
        public ActionResult CreateUtili()
        {
            return View();
        }

        // POST: Utilisateurs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUtili([Bind(Include = "id_Uti,Nom_Uti,motPasse,Role")] Utilisateur utilisateur)
        {
            if (ModelState.IsValid)
            {
                dbU.Utilisateurs.Add(utilisateur);
                dbU.SaveChanges();
                this.AddNotification("AJOUT EFFECTUER", NotificationType.SUCCESS);
                this.AddNotification("Enregistrer avec succes", NotificationType.INFO);
                return RedirectToAction("ListUtili");
            }
            this.AddNotification("VERIFIER VOS INFORMATIONS !", NotificationType.ERROR);
            this.AddNotification("AJOUT NON EFFECTUER !", NotificationType.WARNING);
            return View(utilisateur);
        }
        [Authorize]
        // GET: Utilisateurs/Edit/5
        public ActionResult EditUtili(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur utilisateur = dbU.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }

        // POST: Utilisateurs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUtili([Bind(Include = "id_Uti,Nom_Uti,motPasse,Role")] Utilisateur utilisateur)
        {
            if (ModelState.IsValid)
            {
                dbU.Entry(utilisateur).State = EntityState.Modified;
                dbU.SaveChanges();
                this.AddNotification("MODIFICATION EFFECTUER", NotificationType.SUCCESS);
                this.AddNotification("Enregistrer avec succes", NotificationType.INFO);
                return RedirectToAction("ListUtili");
            }
            this.AddNotification("MODIFICATION NON EFFECTUER !", NotificationType.WARNING);
            return View(utilisateur);
        }
        [Authorize]
        // GET: Utilisateurs/Delete/5
        public ActionResult DeleteUtili(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur utilisateur = dbU.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }

        // POST: Utilisateurs/Delete/5
        [HttpPost, ActionName("DeleteUtili")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmedUtili(int id)
        {
            Utilisateur utilisateur = dbU.Utilisateurs.Find(id);
            dbU.Utilisateurs.Remove(utilisateur);
            dbU.SaveChanges();
            this.AddNotification("SUPPRESSION EFFECTUER", NotificationType.SUCCESS);

            return RedirectToAction("ListUtili");
        }
        //-----------------------------------------------------------------------------------------------------------------
        /// CONTACTS OPERATIONS : 
          // GET: Contacts
        [Authorize]
        public ActionResult ListContact(string searching)
        {
            return View(db.Contacts.Where(c => c.Nom_msg.Contains(searching) || searching == null).ToList());
            //return View(db.Contacts.ToList());
        }
        [Authorize]

        // GET: Contacts/Details/5
        public ActionResult DetailsContact(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        [Authorize]
        // GET: Contacts/Edit/5
        public ActionResult EditContact(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        //To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditContact([Bind(Include = "id_msg,Nom_msg,Email_msg,Objet_msg,Message_msg")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListContact");
            }
            return View(contact);
        }
        [Authorize]
        // GET: Contacts/Delete/5
        public ActionResult DeleteContact(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {

pfeCLS_website/Views/AdminLog/CreateCat.cshtml
@model pfeCLS_website.Models.Categorie

@{
    ViewBag.Title = "CreateCat";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                @Html.Partial("_Notifications")
                <h3 class="page-header"><i class="icofont-plus"></i>AJOUTER UNE CATEGORIE</h3>
                <ol class="breadcrumb">
                    <li><i class="icofont-home"></i><a href="@Url.Action("index","AdminLog")">Accueil</a></i>
                    <li>Categories</li>

                </ol>
            </div>
        </div>
        <!-- Form validations -->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        Formulaire d'ajout :
                    </header>
                    <div class="panel-body">
                        <div class="form">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <h4>Categorie</h4>
                                    <hr />
                                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                                    <div class="form-group">
                                        <div class="col-md-10">
                                            Nom :
                                        </div>
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Nom_Cat, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Nom_Cat, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="ajouter" class="btn btn-default" />
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </section>
                <div>
                    <i class="icofont-reply"></i> @Html.ActionLink("Retournez à la page précédente", "ListCat")
                </div>
                <br /><br /><br /><br />
            </div>
        </div>
    </section>
</section>

pfeCLS_website/Views/AdminLog/CreateInscription.cshtml
@model pfeCLS_website.Models.Inscription

@{
    ViewBag.Title = "CreateInscription";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    @Html.Partial("_Notifications")
                    <h3 class="page-header"><i class="icofont-plus"></i>Ajouter un participant</h3>
                    <ol class="breadcrumb">
                        <li><i class="icofont-home"></i><a href="@Url.Action("index","AdminLog")">Accueil</a></i>
                        <li>Inscription</li>

                    </ol>
                </div>
            </div>
            <!-- Form validations -->
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Formulaire d'inscription :
                        </header>
                        <div class="panel-body">
                            <div class="form">
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        <h4>Inscription</h4>
                                        <hr />
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="form-group">
                                           @*@Html.LabelFor(model => model.Nom_part, htmlAttributes: new { @class = "control-label col-md-2" })*@

                                            <div class="col-md-10">
                                                Nom :
                                                @Html.EditorFor(model => model.Nom_part, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Nom_part, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @*@Html.LabelFor(model => model.Prenom_part, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                            <div class="col-md-10">
                                                Prenom :
                                                @Html.EditorFor(model => model.Prenom_part, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Prenom_part, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @*@Html.LabelFor(model => model.Age_part, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                            <div class="col-md-10">
                                                Age :
                                                @Html.EditorFor(model => model.Age_part, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Age_part, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @*@Html.LabelFor(model => model.Email_part, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                            <div class="col-md-10">
                                                Email
                                                @Html.EditorFor(model => model.Email_part, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Email_part, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @*@Html.LabelFor(model => model.Profil_part, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                            <div class="col-md-10">
                                                Profil :
                                                @Html.EditorFor(model => model.Profil_part, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Profil_part, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @*@Html.LabelFor(model => model.Adresse_part, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                            <div class="col-md-10">
                                                Adresse :
                                                @Html.EditorFor(model => model.Adresse_part, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Adresse_part, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @*@Html.LabelFor(model => model.Tele_part, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                            <div class="col-md-10">
                                                Tele :
                                                @Html.EditorFor(model => model.Tele_part, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Tele_part, "", new { @class = "text-danger" })
                                            </div>
                                        </div>



                                        <div class="form-group">
                                            @*@Html.LabelFor(model => model.ID_branche, "ID_branche", htmlAttributes: new { @class = "control-label col-md-2" })*@
                                            <div class="col-md-10">
                                                Branche :
                                                @Html.DropDownList("ID_branche", null, htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.ID_branche, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Ajouter" class="btn btn-default" />
                                            </div>
                                        </div>
                                    </div>
                                }
                                </div>
                            </div>
                    </section>
                    <div>
                        <i class="icofont-reply"></i>@Html.ActionLink("retournez à la page précédente", "ListInscription")
                    </div>
                    <br /><br /><br /><br />
                </div>
                        </div>
            </section>
        </section>
    
            
                      

          

pfeCLS_website/Views/AdminLog/CreateOffr.cshtml
@model pfeCLS_website.Models.Offre

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                @Html.Partial("_Notifications")
                <h3 class="page-header"><i class="icofont-plus"></i>AJOUTER OFFRE</h3>
                <ol class="breadcrumb">
                    <li><i class="icofont-home"></i><a href="@Url.Action("index","AdminLog")">Accueil</a></i>
                    <li>Offre</li>

                </ol>
            </div>
        </div>
        <!-- Form validations -->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        Formulaire d'ajout :
                    </header>
                    <div class="panel-body">
                        <div class="form">
                 

                                @using (Html.BeginForm("CreateOffr","AdminLog",FormMethod.Post,new {enctype="multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        <h4>Offre</h4>
                                        <hr />
                                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                Titre :
                                            </div>
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Tittre_Off, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Tittre_Off, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-10">
                                                Description :
                                            </div>
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Descr_Off, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Descr_Off, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-10">
                                                Image :
                                            </div>
                                            <div class="col-md-10">
                                                <input type="file" name="ImageFile" id="ImageFile" required />
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-10">
                                                Categorie :
                                            </div>
                                            <div class="col-md-10">
                                                @Html.DropDownList("Id_Cat", null, htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.Id_Cat, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Ajouter" class="btn btn-default" />
                                            </div>
                                        </div>
                                    </div>
                                }

                        </div>
                    </div>
                </section>
                <div>
                    <i class="icofont-reply"></i> @Html.ActionLink("Retournez à la page précédente", "ListOffr")
                </div>
                <br /><br /><br /><br />
            </div>
        </div>
    </section>
</section>
@*<script>
    function AjaxPost(formData) {
        var ajaxConfig = {
            type: "POST",
            url: "/Product/SaveData",
            data: new FormData(formData),
            success: function (result) {
                alert(result);
                window.location.href = "/AdminLog/ListOffr";
            }
        }
        if ($(formData).attr('enctype') == "multipart/form-data") {
            ajaxConfig["contentType"] = false;
            ajaxConfig["processData"] = false;
        }
        $.ajax(ajaxConfig);
        return false;
    }
</script>*@

pfeCLS_website/Views/AdminLog/DeleteCat.cshtml
@model pfeCLS_website.Models.Categorie

@{
    ViewBag.Title = "DeleteCat";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                @Html.Partial("_Notifications")
                <h3 class="page-header"><i class="icofont-ui-delete"></i>SUPPRIMER CATEGORIE</h3>
                <ol class="breadcrumb">
                    <li><i class="icofont-home"></i><a href="@Url.Action("index","AdminLog")">Accueil</a></li>
                    <li>Categorie</li>

                </ol>
            </div>
        </div>
        <!-- Form validations -->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        Voullez-vous vraiment supprime cette categorie ?
                    </header>
                    <div class="panel-body">
                        <div class="form">
                            <hr />
                            <dl class="dl-horizontal">
                                <dt>
                                   Nom :
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Nom_Cat)
                                </dd>

                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Supprimer" class="btn btn-default" /> |
                                <i class="icofont-reply"></i>@Html.ActionLink("retournez à la page précédente", "ListCat")

                            </div>
                            }
                        </div>
                    </div>
                </section>

                <br /><br /><br /><br />
            </div>
        </div>
    </section>
</section>

pfeCLS_website/Views/AdminLog/DetailsCat.cshtml
@model pfeCLS_website.Models.Categorie

@{
    ViewBag.Title = "DetailsCat";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                @Html.Partial("_Notifications")
                <h3 class="page-header"> <i class="icofont-spinner"></i>DETAILS DE CATEGORIE</h3>
                <ol class="breadcrumb">
                    <li><i class="icofont-home"></i><a href="@Url.Action("index","AdminLog")">Accueil</a></li>
                    <li>Categorie</li>

                </ol>
            </div>
        </div>
        <!-- Form validations -->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        Details :
                    </header>
                    <div class="panel-body">
                        <div class="form">
                            <hr />
                            <dl class="dl-horizontal">
                                <dt>
                                    Nom de categorie :
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Nom_Cat)
                                </dd>

                            </dl>
                            <div>
                                @Html.ActionLink("Modifier", "EditCat", new { id = Model.Id_Cat }) |
                                <i class="icofont-reply"></i>@Html.ActionLink("retournez à la page précédente", "ListCat")
                            </div>
                        </div>
                    </div>

                </section>

                <br /><br /><br /><br />
            </div>
        </div>
    </section>
</section>